# Values for sample-app using Mekorot chart structure
nameOverride: "sample-app"
fullnameOverride: ""

app:
  deployment:
    enabled: true
    name: "sample-app"
    labels:
      app: sample-app
      tier: frontend
  replicaCount: 2
  autoscaling:
    enabled: false
  image:
    repository: nginxdemos/hello
    tag: "latest"
    pullPolicy: IfNotPresent
  containerPort: 80
  livenessProbe: "/"
  readinessProbe: "/"
  initialDelaySeconds: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  nodeSelector:
    type: default
  affinity: {}
  tolerations: []
  service:
    enabled: true
    name: "sample-app-service"
    type: ClusterIP
    port: 80
    labels:
      app: sample-app
  ingress:
    enabled: false
  config:
    enabled: false
  serviceAccount:
    create: false
    enabled: false
  externalSecret:
    enabled: false
  storageClass:
    enabled: false
  persistentVolume:
    enabled: false
  persistentVolumeClaim:
    enabled: false
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  imagePullSecrets: []
