{{- if .Values.externalSecret -}}
{{- range $secret := .Values.externalSecret.secrets -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret.name | quote }}
  namespace: {{ $secret.namespace | quote }}
  annotations: 
spec:
  refreshInterval: {{ $secret.interval | quote }}
  secretStoreRef:
    name: {{ $secret.secretStoreRefName | quote }}            # ClusterSecretStore created by Terraform
    kind: {{ $secret.secretStoreRefKind | quote }}
  target:
    name: {{ $secret.targetSecret | quote }}
    creationPolicy: Owner
    deletionPolicy: "Delete"
  {{- if $secret.template }}
    template:
      metadata:
        {{- if $secret.template.labels }}
        labels:
          {{- range $k, $v := $secret.template.labels }}
          {{ $k | quote }}: {{ $v | quote }}
          {{- end }}
        {{- end }}
        {{- if $secret.template.annotations }}
        annotations:
          {{- range $k, $v := $secret.template.annotations }}
          {{ $k | quote }}: {{ $v | quote }}
          {{- end }}
        {{- end }}
      type: {{ $secret.template.type | default "Opaque" | quote }}
  {{- end }}
  data:
  {{- range $secret.data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteKey | quote }}
        property: {{ .remoteProperty | default "" | quote }}
  {{- end }}
---
{{- end }}
{{- end }}