{{- if .Values.app.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
  {{- with .Values.app.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end}}