apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # ArgoCD Helm Chart
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.28.1
      chart: argo-cd
      helm:
        valueFiles:
          - $values/environments/central-workload/argocd/values/values.yaml
    # Values source  
    - repoURL: git@github.com:barzviely/mekorot-helm.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
