apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-1
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    # Mekorot chart source (production-ready universal chart)
    - repoURL: https://github.com/barzviely/mekorot-helm.git
      targetRevision: HEAD
      path: charts/mekorot
      helm:
        valueFiles:
          - $values/environments/central-workload/sample-app-1/values/values.yaml
    # Values source  
    - repoURL: https://github.com/barzviely/mekorot-helm.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
