# Values for sample-app-1 using Mekorot chart structure with ConfigMap  
nameOverride: "sample-app-1"
fullnameOverride: ""

app:
  deployment:
    enabled: true
    name: "sample-app-1"
    labels:
      app: sample-app-1
      tier: frontend
      autoscaling: enabled
  replicaCount: 3
  autoscaling:
    enabled: true  # Note: mekorot chart needs HPA template to be added
  image:
    repository: nginxdemos/hello
    tag: "latest"
    pullPolicy: IfNotPresent
  containerPort: 80
  livenessProbe: "/"
  readinessProbe: "/"
  initialDelaySeconds: 10
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi
  nodeSelector:
    type: default
  affinity: {}
  tolerations: []
  service:
    enabled: true
    name: "sample-app-1-service"
    type: ClusterIP
    port: 80
    labels:
      app: sample-app-1
  config:
    enabled: false
  ingress:
    enabled: false
  serviceAccount:
    create: false
    enabled: false
  externalSecret:
    enabled: false
  storageClass:
    enabled: false
  persistentVolume:
    enabled: false
  persistentVolumeClaim:
    enabled: false
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  imagePullSecrets: []
